# Generated by Django 5.2.5 on 2025-10-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='zip_code',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
